spring:
  application:
    name: attendanceSrv
  profiles:
    active: test
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://lyuanzhi.com:3306/CheckInDB?serverTimezone=GMT
    username: root
    password: Eshxcpqw.123
    hikari:
      maxLifetime: 65000
      maximumPoolSize: 4
  redis:
    database: 0
    host: lyuanzhi.com
    port: 6379
    password: lyuanzhi
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 1000
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/public/

mybatis:
  mapper-locations:
    - classpath*:Mapper/*.xml
  type-aliases-package: edu.duke.ece651.team7.attendanceServer.POJO

mapper:
  mappers: edu.duke.ece651.team7.attendanceServer.MyMapper
  not-empty: false
  identity: MYSQL

server:
  port: 8090
  servlet:
    session:
      timeout: 60
  error:
    path: /error
    whitelabel:
      enabled: false
  ssl:
    key-store: classpath:lyuanzhi.com.jks
    key-store-password: pt3ck07bx45
    key-store-type: JKS
